version: "3"
services:
  embulk:
    build:
      context: ./embulk
    volumes:
      - ./embulk:/embulk
    working_dir: /embulk
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    expose:
      - 9200
    ports:
      - "9200:9200"
      - "9300:9300"
    tty: true
    environment:
      discovery.type: single-node
