source 'https://rubygems.org/'

gem 'bundler'
gem 'embulk', '0.10.44'
gem 'embulk-filter-expand_json'
gem 'embulk-output-opensearch'
gem 'liquid'
gem 'msgpack'

# source 'https://rubygems.pkg.github.com/calorie' do
#   gem 'embulk-output-opensearch', '1.0.0'
# end
