source 'https://rubygems.org/'

gem 'bundler'
gem 'embulk'
gem 'embulk-filter-expand_json'
gem 'liquid'
gem 'msgpack'

source 'https://rubygems.pkg.github.com/calorie' do
  gem 'embulk-output-elasticsearch', '0.6.0.snapshot'
end
